handle = "marcel"

[network]
whoisport = 4000
port = [ 5000, 5010,]
chat_port = 5001
broadcast_address = "255.255.255.255"
local_ip = "10.10.10.68"

[system]
autoreply = "Ich bin gerade nicht verfügbar."
image_autoview = true
imagepath = "images/"
socket_timeout = 5

[user]
max_image_size = 5242880
